#66: Add  new paymentmethods: ideal and bancontact
commercetools/commercetools-payment-integration-java pull request #67
Opened 2020-09-04 16:44 UTC by ahalberkamp

In this pr two new payment methods was added to the lib; ideal and bancontact

2020-09-06 14:49 UTC, JudeNiroshan requested changes
Nice work Andy! I would like to point 2 things additionally. 🥇 
1. Please add the 2 payment methods in the README.md
2. Integrate dependabot like in payone, so we won't forget to update libraries.

2020-09-07 07:41 UTC, ahalberkamp commented
> Please add the 2 payment methods in the README.md
b12b90a

2020-09-07 09:18 UTC, ahalberkamp commented
> Integrate dependabot like in payone, so we won't forget to update libraries.
4c18c3579e387bdde36ff5bec12339627230c457

2020-09-07 09:21 UTC, JudeNiroshan approved these changes

2020-09-07 09:53 UTC, merged